Messages:
  prefix: "&8[&5TownyPlots&8]"
  help:
    - "&a&l----------- &6&lTowny Plots &a&l-----------"
    - "&e/townyplots help &f- help per commands"
    - "&e/townyplots see &f- view menu of available plots"
    - "&e/townyplots reload &f- reloads config"
    - "&a&l----------- &6&lTowny Plots &a&l-----------"
  notPlayer: "&cThis command can only be executed by players."
  noPermission: "&cYou do not have permissions to execute this command."
  noCity: "&cYou must be a member of a town to use this command."
  residentError: "&cError obtaining resident information."
  reload: "&2Plugin reloaded."
  menuTitle: "&8Towny plots"
  #Do not add blank space after ':' on '&6Plot:'
  plot: "&6Plot:"
  price: "&6Price:"
  errorPlotPurchase: "&cError on purchase plot."
  noMoney: "&cYou don't have enought money to buy this plot."
  buySuccess: "&aYou have successfully purchased the plot."
  noPlots: "&cThere is no plots to buy."
  name: "&6Plot name:"
  noName: "&6No name"
  errorMenu: "&cError on open menu."
  confirmPurchase: "&8Deseas confirmar la compra? /confirmar o /cancelar"
  commandError: "&cError on execute the command, see /townyplots help."
  nextPage: "&7Next Page"
  previousPage: "&7Previous Page"
  noAvailableInventories: "&cThere is no available inventories."
  groupSize: "&6Group of"
  groupSizePlots: "&6plots."